# Validation constants - score weights and thresholds

# Score weights
MAX_SCORE = 100
JSON_ITEMS_WEIGHT = 30
JSON_SCHEMA_WEIGHT = 30
JSON_COMPLETENESS_WEIGHT = 20
JSON_QUALITY_WEIGHT = 20

# Filename validation
FILENAME_LENGTH_MIN = 4
FILENAME_LENGTH_MAX = 59
FILENAME_LENGTH_WEIGHT = 40
FILENAME_CHARS_WEIGHT = 30
FILENAME_FORMAT_WEIGHT = 30

# Summary validation
SUMMARY_HEADERS_WEIGHT = 20
SUMMARY_LENGTH_GOOD = 30
SUMMARY_LENGTH_OK = 15
SUMMARY_LENGTH_THRESHOLD = 500
SUMMARY_LENGTH_THRESHOLD_OK = 200
SUMMARY_CONTENT_WEIGHT = 20
SUMMARY_LINES_GOOD = 5
SUMMARY_LINES_OK = 3

# File summary validation
FILE_SUMMARY_ITEMS_WEIGHT = 40
FILE_SUMMARY_QUALITY_WEIGHT = 60
FILE_SUMMARY_MIN_ITEMS = 3