# Image Renamer Configuration
tesseract_cmd = "/opt/homebrew/bin/tesseract"
mlx_models_dir = "~/MLXModels/mlx-community"
llm_url = "http://localhost:1337"

vlm_preferred = [
  "gemma-4-26b-a4b-it-4bit",
  "qwen3.5-27b-claude-4.6-opus-distilled-mlx-4bit",
]

text_preferred = [
  "gemma-4-e2b-it-8bit",
  "foundation",
]
