"""Weekend planner."""

from weekend.cli import main, parse_args
from weekend.config import (
    AGE_RANGE,
    CHILDREN,
    CHILDREN_STR,
    CITY,
    DATES_STR,
    DEBUG_EVENTS_FILE,
    DEBUG_VENUES_FILE,
    EXCLUDE_PLACES,
    MODEL_CONFIG,
    MODEL_NAME,
    OSAURUS_APP,
    OSAURUS_BASE_URL,
    REGION,
    WEEKEND_CONFIG,
    ensure_server,
    is_server_running_ours,
    load_events_cache,
    load_venues_cache,
    load_weekend_config,
    restart_osaurus,
    save_events_cache,
    save_venues_cache,
)
from weekend.data import (
    fetch_fixed_venues,
    fetch_transient_events,
    fetch_weather,
    get_weekend_date_objects,
    get_weekend_dates_string,
    scrape_review_score,
)
from weekend.llm import (
    fetch_scores_for_items,
    generate_weekend_plan,
    get_llm_json,
    normalize_llm_items,
)
from weekend.output import (
    build_markdown_tables,
    print_header,
    print_info,
    print_step,
    print_summary,
    print_to_cli,
    print_warning,
)
from weekend.prompts import (
    build_fixed_system_prompt,
    build_fixed_user_prompt,
    build_transient_system_prompt,
    build_transient_user_prompt,
)

__all__ = [
    "main",
    "parse_args",
    "AGE_RANGE",
    "CHILDREN",
    "CHILDREN_STR",
    "CITY",
    "DATES_STR",
    "DEBUG_EVENTS_FILE",
    "DEBUG_VENUES_FILE",
    "EXCLUDE_PLACES",
    "MODEL_CONFIG",
    "MODEL_NAME",
    "OSAURUS_APP",
    "OSAURUS_BASE_URL",
    "REGION",
    "WEEKEND_CONFIG",
    "ensure_server",
    "is_server_running_ours",
    "load_events_cache",
    "load_venues_cache",
    "load_weekend_config",
    "restart_osaurus",
    "save_events_cache",
    "save_venues_cache",
    "fetch_fixed_venues",
    "fetch_transient_events",
    "fetch_weather",
    "get_weekend_date_objects",
    "get_weekend_dates_string",
    "scrape_review_score",
    "fetch_scores_for_items",
    "generate_weekend_plan",
    "get_llm_json",
    "normalize_llm_items",
    "build_markdown_tables",
    "print_header",
    "print_info",
    "print_step",
    "print_summary",
    "print_to_cli",
    "print_warning",
    "build_fixed_system_prompt",
    "build_fixed_user_prompt",
    "build_transient_system_prompt",
    "build_transient_user_prompt",
]
