# Validators library
# Re-exports from new module structure

# Also export constants
from lib.validators.constants import (
    FILE_SUMMARY_ITEMS_WEIGHT,
    FILE_SUMMARY_MIN_ITEMS,
    FILE_SUMMARY_QUALITY_WEIGHT,
    FILENAME_CHARS_WEIGHT,
    FILENAME_FORMAT_WEIGHT,
    FILENAME_LENGTH_MAX,
    FILENAME_LENGTH_MIN,
    FILENAME_LENGTH_WEIGHT,
    JSON_COMPLETENESS_WEIGHT,
    JSON_ITEMS_WEIGHT,
    JSON_QUALITY_WEIGHT,
    JSON_SCHEMA_WEIGHT,
    MAX_SCORE,
    SUMMARY_CONTENT_WEIGHT,
    SUMMARY_HEADERS_WEIGHT,
    SUMMARY_LENGTH_GOOD,
    SUMMARY_LENGTH_OK,
    SUMMARY_LENGTH_THRESHOLD,
    SUMMARY_LENGTH_THRESHOLD_OK,
    SUMMARY_LINES_GOOD,
    SUMMARY_LINES_OK,
)
from lib.validators.helpers import (
    count_content_lines,
    extract_json_list,
    has_filename_format,
    has_text_headers,
    is_valid_filename_char,
    normalize_whitespace,
    strip_backtick_value,
)
from lib.validators.json_validator import (
    check_source_extraction,
    extract_list_from_dict,
    get_source_matching_details,
    has_item_details,
    validate_detailed_json,
    validate_json,
)
from lib.validators.text_validator import (
    validate_file_summary,
    validate_filename,
    validate_summary,
)
from lib.validators.text_validator_mixed import (
    detect_instruction_leak,
    validate_factual_accuracy,
    validate_factual_coverage,
    validate_mixed_file_summary,
    validate_mixed_filename,
    validate_mixed_summary,
    validate_no_contradiction,
    validate_no_leak,
    validate_strict_schema,
)

__all__ = [
    # Validators
    "validate_json",
    "validate_detailed_json",
    "validate_summary",
    "validate_filename",
    "validate_file_summary",
    # Mixed-signal / faithfulness / leak validators
    "validate_mixed_summary",
    "validate_mixed_file_summary",
    "validate_mixed_filename",
    "validate_factual_accuracy",
    "validate_factual_coverage",
    "validate_no_contradiction",
    "validate_no_leak",
    "validate_strict_schema",
    "detect_instruction_leak",
    # Helpers
    "extract_list_from_dict",
    "check_source_extraction",
    "get_source_matching_details",
    "has_item_details",
    "has_text_headers",
    "count_content_lines",
    "strip_backtick_value",
    "normalize_whitespace",
    "extract_json_list",
    "is_valid_filename_char",
    "has_filename_format",
    # Constants
    "FILE_SUMMARY_ITEMS_WEIGHT",
    "FILE_SUMMARY_MIN_ITEMS",
    "FILE_SUMMARY_QUALITY_WEIGHT",
    "FILENAME_CHARS_WEIGHT",
    "FILENAME_FORMAT_WEIGHT",
    "FILENAME_LENGTH_MAX",
    "FILENAME_LENGTH_MIN",
    "FILENAME_LENGTH_WEIGHT",
    "JSON_COMPLETENESS_WEIGHT",
    "JSON_ITEMS_WEIGHT",
    "JSON_QUALITY_WEIGHT",
    "JSON_SCHEMA_WEIGHT",
    "MAX_SCORE",
    "SUMMARY_CONTENT_WEIGHT",
    "SUMMARY_HEADERS_WEIGHT",
    "SUMMARY_LENGTH_GOOD",
    "SUMMARY_LENGTH_OK",
    "SUMMARY_LENGTH_THRESHOLD",
    "SUMMARY_LENGTH_THRESHOLD_OK",
    "SUMMARY_LINES_GOOD",
    "SUMMARY_LINES_OK",
]
