# Validation constants - score weights and thresholds

# Score weights
MAX_SCORE = 100
JSON_ITEMS_WEIGHT = 30
JSON_SCHEMA_WEIGHT = 30
JSON_COMPLETENESS_WEIGHT = 20
JSON_QUALITY_WEIGHT = 20

# Filename validation
FILENAME_LENGTH_MIN = 4
FILENAME_LENGTH_MAX = 59
FILENAME_LENGTH_WEIGHT = 40
FILENAME_CHARS_WEIGHT = 30
FILENAME_FORMAT_WEIGHT = 30

# Summary validation
SUMMARY_HEADERS_WEIGHT = 20
SUMMARY_LENGTH_GOOD = 30
SUMMARY_LENGTH_OK = 15
SUMMARY_LENGTH_THRESHOLD = 350
SUMMARY_LENGTH_THRESHOLD_OK = 150
SUMMARY_CONTENT_WEIGHT = 20
SUMMARY_LINES_GOOD = 5
SUMMARY_LINES_OK = 3

# File summary validation
FILE_SUMMARY_ITEMS_WEIGHT = 40
FILE_SUMMARY_QUALITY_WEIGHT = 60
FILE_SUMMARY_MIN_ITEMS = 3

# Filename quality detail constants
MIN_SPECIFIC_FILENAME_LEN = 4
FILENAME_LENGTH_SCORE = 30
FILENAME_CHARS_SCORE = 20
FILENAME_FORMAT_SCORE = 25
MAX_EXPLANATORY_FILENAME_LEN = 70
FILENAME_EXPLANATION_PENALTY_SCORE = 15
FILENAME_SPECIFIC_SCORE = 25

# Summary quality detail constants
STRUCT_HEADERS_BULLETS_SCORE = 15
STRUCT_HEADERS_ONLY_SCORE = 10
STRUCT_BULLET_LONG_LEN = 300
STRUCT_BULLET_LONG_SCORE = 8
STRUCT_BULLET_SHORT_LEN = 200
STRUCT_BULLET_SHORT_SCORE = 5
USERS_COVERAGE_HIGH_COUNT = 3
USERS_COVERAGE_HIGH_SCORE = 15
USERS_COVERAGE_MED_COUNT = 2
USERS_COVERAGE_MED_SCORE = 10
USERS_COVERAGE_LOW_COUNT = 1
USERS_COVERAGE_LOW_SCORE = 5
TIMESTAMP_SPECIFICITY_SCORE = 10
MAX_NARRATIVE_SPECIFICITY_SCORE = 15
NARRATIVE_WORD_SCORE_MULTIPLIER = 5
TEMPLATE_DRIVEN_FIELD_LIMIT = 3
BOILERPLATE_SYNTHESIS_SCORE = 5
DEFAULT_SYNTHESIS_SCORE = 10
SYNTHESIS_MATCH_BONUS = 10
TOPIC_COVERAGE_HIGH_COUNT = 2
TOPIC_COVERAGE_HIGH_SCORE = 25
TOPIC_COVERAGE_MED_COUNT = 1
TOPIC_COVERAGE_MED_SCORE = 15
TOPIC_TRANSITION_WORD_SCORE = 10

# File summary quality detail constants
FILE_SUMMARY_ITEMS_SCORE = 30
PATH_REALISM_HIGH_RATIO = 0.7
PATH_REALISM_HIGH_SCORE = 30
PATH_REALISM_MED_RATIO = 0.4
PATH_REALISM_MED_SCORE = 20
SPECIFIC_DESC_HIGH_COUNT = 2
SPECIFIC_DESC_HIGH_SCORE = 40
SPECIFIC_DESC_MED_COUNT = 1
SPECIFIC_DESC_MED_SCORE = 25
SPECIFIC_DESC_LOW_SCORE = 15
MIN_SPECIFIC_DESC_LEN = 10

# Filename helper constants
FILENAME_SEPARATORS = ("_", "-", ".")
MIN_FILENAME_LINE_LEN = 3
MAX_FILENAME_LINE_LEN = 60
DEFAULT_CANDIDATE_FALLBACK_LIMIT = 50
CODE_FENCE_LEN = 3
SPACE_CHAR = " "
MIN_KEYS_FOR_DETAILS = 1

# Item count thresholds
MIN_ITEMS_GOOD = 10
MIN_ITEMS_OK = 5

# Source grounding thresholds for score capping
SOURCE_THRESHOLD_HIGH = 0.8
SOURCE_THRESHOLD_MED = 0.5
SOURCE_THRESHOLD_LOW = 0.3

# Max score caps based on source grounding
MAX_SCORE_HIGH_SOURCE = 100
MAX_SCORE_MED_SOURCE = 60
MAX_SCORE_LOW_SOURCE = 30
MAX_SCORE_NO_SOURCE = 15

# Max failures to include in error message
DETAIL_REQUIRED_FIELDS = 3
