#!/usr/bin/env python3
"""
Output helpers for twitter_summarizer.
"""

import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from lib.config_toml import load_config
from lib.tui import STEP, WARN

_TWITTER_CONFIG_PATH = Path(__file__).parent.parent / "conf" / "twitter.toml"
_TWITTER_CFG = load_config(_TWITTER_CONFIG_PATH) or {}

STATE_FILE = Path(
    _TWITTER_CFG.get("state_file", str(Path.home() / ".twitter_summary_state.json"))
).expanduser()
DEBUG_CACHE_FILE = Path.home() / ".twitter_summary_debug_cache.json"
DEFAULT_OUTPUT_DIR = Path(
    _TWITTER_CFG.get("output_dir", str(Path.home() / "Documents" / "twitter_summaries"))
).expanduser()
DEFAULT_OLLAMA_URL = _TWITTER_CFG.get("llm_url", "http://localhost:1337")


def load_state() -> dict:
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text())
        except (json.JSONDecodeError, OSError):
            pass
    return {}


def save_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state, indent=2))


def load_debug_cache() -> list[dict]:
    if DEBUG_CACHE_FILE.exists():
        try:
            tweets = json.loads(DEBUG_CACHE_FILE.read_text())
            for tweet in tweets:
                if "created_at" in tweet and isinstance(tweet["created_at"], str):
                    tweet["created_at"] = datetime.fromisoformat(tweet["created_at"])
            return tweets
        except (json.JSONDecodeError, OSError):
            pass
    return []


def save_debug_cache(tweets: list[dict]) -> None:
    def serialize(obj):
        if isinstance(obj, datetime):
            return obj.isoformat()
        raise TypeError(f"Object of type {type(obj).__name__} is not JSON serializable")

    DEBUG_CACHE_FILE.write_text(json.dumps(tweets, indent=2, default=serialize))


def print_to_stdout(content: str) -> None:
    if shutil.which("bat"):
        try:
            subprocess.run(
                ["bat", "-l", "md", "--color", "always", "--style", "plain"],
                input=content,
                text=True,
                check=True,
            )
        except Exception:
            print(content)
    else:
        print(content)


def write_markdown(
    tweets: list[dict],
    summary: str,
    since_time: datetime,
    until_time: datetime,
    output_dir: Path,
) -> tuple[Path, str]:
    output_dir.mkdir(parents=True, exist_ok=True)
    fmt = "%Y-%m-%d_%H%M"
    filename = f"{since_time.strftime(fmt)}_to_{until_time.strftime(fmt)}.md"
    out_path = output_dir / filename
    unique_authors = len({t["screen_name"] for t in tweets})
    period_str = (
        f"{since_time.strftime('%Y-%m-%d %H:%M')} → {until_time.strftime('%Y-%m-%d %H:%M')} UTC"
    )

    content = f"""# Twitter Timeline Summary

**Period:** {period_str}
**Tweets:** {len(tweets)} from {unique_authors} accounts

## Summary

{summary}

---
*Generated by twitter_summarizer.py on {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}*
"""
    out_path.write_text(content)
    return out_path, content


def clean_folder(output_dir: Path) -> None:
    if not output_dir.exists():
        print(f"{WARN} Directory {output_dir} does not exist.")
        sys.exit(0)

    print(f"{STEP} Removing existing .md files in {output_dir} ...")
    for md_file in output_dir.glob("*.md"):
        try:
            md_file.unlink()
        except OSError as e:
            print(f"{WARN} Failed to delete {md_file}: {e}")

    print(f"{STEP} Cleanup complete.")
    sys.exit(0)
