#!/usr/bin/env python3
"""Generate Rust prompt constants from references/eval/tasks_prompts.py.

The Python module is the single source of truth for eval prompt text. This
script transcribes the listed constants into Rust `pub const` declarations,
byte-identical, as raw strings. `references/tests/test_rust_prompt_parity.py`
re-derives the same values at test time and fails the gate on any drift, so
hand-editing either side breaks CI.

Usage: PYTHONPATH=references python3 tools/gen_rust_prompts.py
Exits 1 if any output file would exceed the 500-line production cap.
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "rust" / "src" / "ztools" / "eval" / "prompts"
MAX_LINES = 500

from eval import tasks_prompts as tp  # noqa: E402

STRING_CONSTS = [
    "RENAME_PROMPT",
    "RENAME_PROMPT_MIXED",
    "IMAGE_RENAME_PROMPT",
    "IMAGE_RENAME_PROMPT_MIXED",
    "FILE_SUMMARY_PROMPT",
    "FILE_SUMMARY_PROMPT_MIXED",
    "TWITTER_PROMPT",
    "TWITTER_PROMPT_ACCURACY",
    "TWITTER_PROMPT_CONTRADICTION",
    "TWITTER_PROMPT_MISATTRIBUTION",
    "TWITTER_PROMPT_MIXED",
    "WEEKEND_USR_FIXED",
    "WEEKEND_USR_TRANSIENT",
    "WEEKEND_USR_FIXED_MIXED",
    "WEEKEND_USR_TRANSIENT_MIXED",
    "CONTRADICTION_PHRASE",
    "MISATTRIBUTION_TIMELINE",
    "FILENAME_INJECTION_PROMPT",
    "FALSEHOOD_TWEET_1",
    "FALSEHOOD_TWEET_2",
    "FALSEHOOD_TWEET_3",
    "FILE_SUMMARY_FILE_LIST",
]

LIST_CONSTS = [
    "FILENAME_INJECTION_MARKERS",
    "FILENAME_INJECTION_KEYWORDS",
    "FALSEHOOD_PHRASES",
    "KEY_FACTS",
]

# name -> submodule file
FILE_LAYOUT = {
    "rename": ["RENAME_PROMPT", "RENAME_PROMPT_MIXED", "IMAGE_RENAME_PROMPT",
               "IMAGE_RENAME_PROMPT_MIXED", "FILENAME_INJECTION_MARKERS",
               "FILENAME_INJECTION_KEYWORDS", "FILENAME_INJECTION_PROMPT"],
    "file_summary": ["FILE_SUMMARY_PROMPT", "FILE_SUMMARY_PROMPT_MIXED",
                    "FILE_SUMMARY_FILE_LIST"],
    "twitter": ["TWITTER_PROMPT", "TWITTER_PROMPT_ACCURACY",
                "TWITTER_PROMPT_CONTRADICTION", "TWITTER_PROMPT_MISATTRIBUTION",
                "TWITTER_PROMPT_MIXED", "CONTRADICTION_PHRASE",
                "FALSEHOOD_PHRASES", "MISATTRIBUTION_TIMELINE",
                "FALSEHOOD_TWEET_1", "FALSEHOOD_TWEET_2", "FALSEHOOD_TWEET_3"],
    "weekend": ["WEEKEND_USR_FIXED", "WEEKEND_USR_TRANSIENT",
                "WEEKEND_USR_FIXED_MIXED", "WEEKEND_USR_TRANSIENT_MIXED",
                "KEY_FACTS"],
}


def raw_string(value: str) -> str:
    """Render a Rust raw string literal that reproduces `value` byte-for-byte."""
    for hashes in ("#", "##", "###", "####"):
        if f'"{hashes}' not in value:
            return f'r{hashes}"{value}"{hashes}'
    raise SystemExit("value contains every raw-string terminator; extend hash levels")


def rust_list(items: list) -> str:
    parts = []
    for item in items:
        escaped = item.replace("\\", "\\\\").replace('"', '\\"')
        parts.append(f'"{escaped}"')
    return "&[" + ", ".join(parts) + "]"


def render_module(doc: str, names: list) -> str:
    lines = [f"//! {doc}", "//!", "//! GENERATED by tools/gen_rust_prompts.py from",
             "//! references/eval/tasks_prompts.py -- do not hand-edit;",
             "//! regenerate instead. Parity enforced by",
             "//! references/tests/test_rust_prompt_parity.py.", ""]
    for name in names:
        value = getattr(tp, name)
        if isinstance(value, str):
            lines.append(f"pub const {name}: &str = {raw_string(value)};")
        elif isinstance(value, list):
            if not all(isinstance(i, str) for i in value):
                raise SystemExit(f"{name}: only list-of-str supported")
            lines.append(f"pub const {name}: &[&str] = {rust_list(value)};")
        else:
            raise SystemExit(f"{name}: unsupported type {type(value)}")
        lines.append("")
    return "\n".join(lines)


DOCS = {
    "rename": "Rename / image-rename task prompts and injection lures.",
    "file_summary": "File-summary task prompts.",
    "twitter": "Twitter summarizer task prompts and attribution lures.",
    "weekend": "Weekend planner task prompts.",
}


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for module, names in FILE_LAYOUT.items():
        content = render_module(DOCS[module], names)
        n_lines = content.count("\n") + 1
        if n_lines > MAX_LINES:
            print(f"✗ {module}.rs would be {n_lines} lines (cap {MAX_LINES}); "
                  "split FILE_LAYOUT further")
            return 1
        path = OUT_DIR / f"{module}.rs"
        path.write_text(content)
        written.append((path.name, n_lines))

    mod_lines = ["//! Eval task prompt texts, generated from the Python source of truth.",
                 "//!",
                 "//! Each submodule is regenerated by tools/gen_rust_prompts.py;",
                 "//! byte-parity with references/eval/tasks_prompts.py is gated by",
                 "//! references/tests/test_rust_prompt_parity.py.", ""]
    all_names = []
    for module, names in FILE_LAYOUT.items():
        mod_lines.append(f"pub mod {module};")
        all_names.extend(names)
    mod_lines.append("")
    for module, names in FILE_LAYOUT.items():
        mod_lines.append(f"pub use {module}::{{{', '.join(names)}}};")
    mod_path = OUT_DIR / "mod.rs"
    mod_path.write_text("\n".join(mod_lines) + "\n")
    written.append(("mod.rs", len(mod_lines)))

    for name, n in written:
        print(f"→ wrote {name} ({n} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
